apiVersion: batch/v1
kind: Job
metadata:
  name: cucumber-job
spec:
  template:
    spec:
      containers:
      - name: cucumber
        image: my-registry/my-app:latest
        command: ["java", "-cp", "my-app.jar:dependencies/*", "io.cucumber.core.cli.Main", "-g", "com.example", "src/test/resources/features"]
      restartPolicy: Never
  backoffLimit: 4

